In [1]:
# Dependencies
import requests
import json
import pandas as pd
import gmaps

# Google developer API key
from config import gkey

gmaps.configure(api_key=gkey)

In [2]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
place_from_text = "https://maps.googleapis.com/maps/api/place/findplacefromtext/json"
details_url = "https://maps.googleapis.com/maps/api/place/details/json"
geo_url = "https://maps.googleapis.com/maps/api/geocode/json"

#address=1600+Amphitheatre+Parkway,+Mountain+View,+CA&key=

target_address="Estado de Mexico"
target_coordinates = ""
target_search = "Estado de Mexico"
target_radius = 50000
target_type = "restaurant"
target_query = "Estado de Mexico"
place_id = "ChIJOwrrwJKJzYURV6jFn775_sI"
g_id = "e579533b947b1a3233a8029b07477df919791427"
qinput = "Estado de Mexico"
inputtype = "textquery"

params1 = {
    "input" : qinput,
    "inputtype" : inputtype,
    #"id": g_id,
    #"place_id": place_id,
    #"location" : target_coordinates,
    #"keyword" : target_search,
    #"radius" : target_radius,
    #"type" : target_type,
    "key": gkey
}

params2 = {
    "query" : target_query,
    "place_id": place_id,
    #"keyword" : target_search,
    #"radius" : target_radius,
    #"type" : target_type,
    "key": gkey
    #"address" : target_address
}

params3 = {
    #"query" : target_query,
    #"location" : target_coordinates,
    #"keyword" : target_search,
    #"radius" : target_radius,
    #"type" : target_type,
    "key": gkey,
    "address" : target_address
}

params4 = {
    "input" : qinput,
    "inputtype" : inputtype,
    #"id": g_id,
    #"place_id": place_id,
    #"location" : target_coordinates,
    #"keyword" : target_search,
    #"radius" : target_radius,
    #"type" : target_type,
    "key": gkey
}

response1 = requests.get(base_url, params=params1)
response2 = requests.get(details_url, params=params2)
response3 = requests.get(geo_url, params=params3)
response4 = requests.get(place_from_text, params=params4)

In [3]:
print(response1.url)
print(response2.url)
print(response3.url)
print(response4.url)

https://maps.googleapis.com/maps/api/place/nearbysearch/json?input=Estado+de+Mexico&inputtype=textquery&key=AIzaSyAwDyEwcf_ffX0otnRMJYklewZ9ywIkxJc
https://maps.googleapis.com/maps/api/place/details/json?query=Estado+de+Mexico&place_id=ChIJOwrrwJKJzYURV6jFn775_sI&key=AIzaSyAwDyEwcf_ffX0otnRMJYklewZ9ywIkxJc
https://maps.googleapis.com/maps/api/geocode/json?key=AIzaSyAwDyEwcf_ffX0otnRMJYklewZ9ywIkxJc&address=Estado+de+Mexico
https://maps.googleapis.com/maps/api/place/findplacefromtext/json?input=Estado+de+Mexico&inputtype=textquery&key=AIzaSyAwDyEwcf_ffX0otnRMJYklewZ9ywIkxJc

In [4]:
 # convert response to json
places_data = response4.json()

# Print the json (pretty printed)
print(json.dumps(places_data, indent=4, sort_keys=True))

{
    "candidates": [
        {
            "place_id": "ChIJOwrrwJKJzYURV6jFn775_sI"
        }
    ],
    "status": "OK"
}

In [16]:
#DENUE_df = pd.read_csv("Resources/DENUE_Filtered_complete.csv")
DENUE_df = pd.read_csv("Output/DENUE_Filtered.csv")
display(DENUE_df)
long_and_lat_df = pd.read_csv("Resources/Long_and_Lat_by_municip.csv")
display(long_and_lat_df)

,Unnamed: 0,Unnamed: 0.1,Código Tipo de Industria,ID,Nombre de la Unidad Económica,Razón social,Código de la clase de actividad SCIAN,Nombre de clase de la actividad,Descripcion estrato personal ocupado,Tipo de vialidad,...,Localidad,Área geoestadí­stica básica,Manzana,NÃÂºmero de telÃÂ©fono,Correo electrÃÂ³nico,Sitio en Internet,Tipo de establecimiento,Latitud,Longitud,Fecha de incorporación al DENUE
0,0,174704,46,2511586,LONJA MERCANTIL HERNANDEZ,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CALLE,...,SAN BARTOLOMÃÂ ATLATLAHUCA,216,4,7.171710e+09,NaN,NaN,Fijo,19.069133,-99.611156,jul-10
1,1,540472,81,2363713,ESTÃÂTICA UNISEX DIANA,NaN,812110,Salones y clÃÂ­nicas de belleza y peluquerÃÂ­as,0 a 5 personas,CALLE,...,IXTAPALUCA,904,12,NaN,NaN,NaN,Fijo,19.290680,-98.902444,dic-14
2,2,23013,31,2032449,TORTILLERÃÂA 599,NaN,311830,ElaboraciÃÂ³n de tortillas de maÃÂ­z y molie...,0 a 5 personas,CALLE,...,CIUDAD NEZAHUALCÃÂYOTL,1289,5,NaN,NaN,NaN,Fijo,19.389040,-99.015859,dic-14
3,3,86301,46,2002299,ABARROTES SIN NOMBRE,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,AVENIDA,...,TULTEPEC,335,8,NaN,NaN,NaN,Fijo,19.680749,-99.136141,jul-10
4,4,399216,56,2249276,INTERNET MIP,NaN,561432,Servicios de acceso a computadoras,0 a 5 personas,CALLE,...,SAN SEBASTIÃÂN,359,16,NaN,NaN,NaN,Fijo,19.787891,-99.055222,dic-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72665,72665,534754,81,2505632,ESTÃÂTICA PLAZA,NaN,812110,Salones y clÃÂ­nicas de belleza y peluquerÃÂ­as,0 a 5 personas,CALLE,...,METEPEC,563,16,7.222082e+09,FROLOPZ31@YAHOO.COM.MX,NaN,Fijo,19.252294,-99.604720,jul-10
72666,72666,407809,61,2018895,ESCUELA PRIMARIA 5 DE MAYO,NaN,611122,Escuelas de educaciÃÂ³n primaria del sector p...,6 a 10 personas,CALLE,...,ECATEPEC DE MORELOS,741,19,5.557887e+09,NaN,NaN,Fijo,19.529771,-99.045686,jul-10
72667,72667,186032,46,2544866,MISCELÃÂNEA ALVAREZ,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CALLE,...,XONACATLÃÂN,43,24,NaN,NaN,NaN,Fijo,19.412025,-99.522470,jul-10
72668,72668,207159,46,2373840,MISCELÃÂNEA LOS TRES ANGELITOS,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CALLE,...,CHALCO DE DÃÂAZ COVARRUBIAS,081A,29,NaN,NaN,NaN,Fijo,19.263108,-98.911619,dic-14
72669,72669,400987,56,2549759,KRASH,NaN,561432,Servicios de acceso a computadoras,0 a 5 personas,CALLE,...,SAN MARCOS TLAZALPAN,110,28,NaN,NaN,NaN,Fijo,19.806111,-99.717500,jul-10

     Clave municipio  Longitud_avg  Latitud_avg
0                  1    -99.859455    19.946281
1                  2    -98.946145    19.616658
2                  3    -99.837060    20.106613
3                  4    -99.891648    18.866239
4                  5    -99.760391    19.346721
..               ...           ...          ...
120              121    -99.213019    19.652518
121              122    -98.941004    19.289142
122              123   -100.298548    18.921607
123              124   -100.129101    19.648330
124              125    -99.053623    19.688031

[125 rows x 3 columns]

In [8]:
#fig = gmaps.figure()

#path =  {"geometry": {
#           "bounds": {
#               "northeast": {
#                   "lat": 20.2858665,
#                   "lng": -98.5968666
#               },
#               "southwest": {
#                   "lat": 18.3669428,
#                   "lng": -100.6130911
#               }
#           },
#       "location": {
#           "lat": 19.4968732,
#           "lng": -99.72326729999999
#       },
#       "location_type": "APPROXIMATE",
#       "viewport": {
#           "northeast": {
#           "lat": 20.2858665,
#           "lng": -98.5968666
#       },
#           "southwest": {
#           "lat": 18.3669428,
#           "lng": -100.6130911
#           }
#       }
#       }}
#path = [{"lat": 20.2858665,
#        "lng": -98.5968666}
#      {"lat": 18.3669428,
#       "lng": -100.6130911},
#      {"lat": 19.4968732,
#       "lng": -99.72326729999999}]
    
#gmaps.Polygon(path)
#paths
list(DENUE_df["Descripcion estrato personal ocupado"].unique())

['0 a 5 personas',
 '6 a 10 personas',
 '11 a 30 personas',
 '31 a 50 personas',
 '51 a 100 personas',
 '101 a 250 personas',
 '251 y más personas']

In [9]:




#micro=DENUE_df.loc[DENUE_df["Descripcion estrato personal ocupado"]]

Size_dict={'0 a 5 personas':1,
           '6 a 10 personas':2,
           '11 a 30 personas':3,
           "31 a 50 personas":4,
           '51 a 100 personas':5,
           '101 a 250 personas':6,
           '251 y más personas':7}
Size_dict2={'0 a 5 personas':"Micro",
           '6 a 10 personas':"Micro",
           '11 a 30 personas':"Pequeña",
           "31 a 50 personas":"Pequeña",
           '51 a 100 personas':"Mediana",
           '101 a 250 personas':"Mediana",
           '251 y más personas':"Grande"}

DENUE_df["Company Size"]=DENUE_df["Descripcion estrato personal ocupado"].astype(str)
DENUE_df["Company Size (int)"]=DENUE_df["Descripcion estrato personal ocupado"].astype(str)
DENUE_df=DENUE_df.replace({"Company Size (int)": Size_dict})
DENUE_df=DENUE_df.replace({"Company Size": Size_dict2})

#DENUE_df["Company Size"] = 
#DENUE_df["Company Size"]=DENUE_df["Descripcion estrato personal ocupado"].replace(['0 a 5 personas','6 a 10 personas'],[1])
                        # DENUE_df["Descripcion estrato personal ocupado"].replace(['11 a 30 personas','31 a 50 personas'],[2])
                         #DENUE_df["Descripcion estrato personal ocupado"].replace(['51 a 100 personas','101 a 250 personas','251 y más personas'],[3])
    #{"Descripcion estrato personal ocupado": Size_dict})
#rating

#rating = DENUE_df["Descripcion estrato personal ocupado"][Size_dict]

DENUE_df

,Unnamed: 0,Unnamed: 0.1,Código Tipo de Industria,ID,Nombre de la Unidad Económica,Razón social,Código de la clase de actividad SCIAN,Nombre de clase de la actividad,Descripcion estrato personal ocupado,Tipo de vialidad,...,Manzana,NÃÂºmero de telÃÂ©fono,Correo electrÃÂ³nico,Sitio en Internet,Tipo de establecimiento,Latitud,Longitud,Fecha de incorporación al DENUE,Company Size,Company Size (int)
0,0,174704,46,2511586,LONJA MERCANTIL HERNANDEZ,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CALLE,...,4,7.171710e+09,NaN,NaN,Fijo,19.069133,-99.611156,jul-10,Micro,1
1,1,540472,81,2363713,ESTÃÂTICA UNISEX DIANA,NaN,812110,Salones y clÃÂ­nicas de belleza y peluquerÃÂ­as,0 a 5 personas,CALLE,...,12,NaN,NaN,NaN,Fijo,19.290680,-98.902444,dic-14,Micro,1
2,2,23013,31,2032449,TORTILLERÃÂA 599,NaN,311830,ElaboraciÃÂ³n de tortillas de maÃÂ­z y molie...,0 a 5 personas,CALLE,...,5,NaN,NaN,NaN,Fijo,19.389040,-99.015859,dic-14,Micro,1
3,3,86301,46,2002299,ABARROTES SIN NOMBRE,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,AVENIDA,...,8,NaN,NaN,NaN,Fijo,19.680749,-99.136141,jul-10,Micro,1
4,4,399216,56,2249276,INTERNET MIP,NaN,561432,Servicios de acceso a computadoras,0 a 5 personas,CALLE,...,16,NaN,NaN,NaN,Fijo,19.787891,-99.055222,dic-14,Micro,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72665,72665,534754,81,2505632,ESTÃÂTICA PLAZA,NaN,812110,Salones y clÃÂ­nicas de belleza y peluquerÃÂ­as,0 a 5 personas,CALLE,...,16,7.222082e+09,FROLOPZ31@YAHOO.COM.MX,NaN,Fijo,19.252294,-99.604720,jul-10,Micro,1
72666,72666,407809,61,2018895,ESCUELA PRIMARIA 5 DE MAYO,NaN,611122,Escuelas de educaciÃÂ³n primaria del sector p...,6 a 10 personas,CALLE,...,19,5.557887e+09,NaN,NaN,Fijo,19.529771,-99.045686,jul-10,Micro,2
72667,72667,186032,46,2544866,MISCELÃÂNEA ALVAREZ,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CALLE,...,24,NaN,NaN,NaN,Fijo,19.412025,-99.522470,jul-10,Micro,1
72668,72668,207159,46,2373840,MISCELÃÂNEA LOS TRES ANGELITOS,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CALLE,...,29,NaN,NaN,NaN,Fijo,19.263108,-98.911619,dic-14,Micro,1
72669,72669,400987,56,2549759,KRASH,NaN,561432,Servicios de acceso a computadoras,0 a 5 personas,CALLE,...,28,NaN,NaN,NaN,Fijo,19.806111,-99.717500,jul-10,Micro,1

In [10]:
#DENUE_df.loc[DENUE_df["Descripcion estrato personal ocupado"].isin(['0 a 5 personas']),'Company size']=1.0
#DENUE_df.loc[DENUE_df["Descripcion estrato personal ocupado"].isin(['6 a 10 personas']),'Company size']=2.0
#DENUE_df.loc[DENUE_df["Descripcion estrato personal ocupado"].isin(['11 a 30 personas']),'Company size']=3.0
#DENUE_df.loc[DENUE_df["Descripcion estrato personal ocupado"].isin(['31 a 50 personas']),'Company size']=4.0
#DENUE_df.loc[DENUE_df["Descripcion estrato personal ocupado"].isin(['51 a 100 personas']),'Company size']=5.0
#DENUE_df.loc[DENUE_df["Descripcion estrato personal ocupado"].isin(['101 a 250 personas']),'Company size']=6.0
#DENUE_df.loc[DENUE_df["Descripcion estrato personal ocupado"].isin(['251 y mÃ¡s personas']),'Company size']=7.0
#DENUE_df.head()

In [17]:
DENUE_df = pd.merge(DENUE_df, long_and_lat_df, on="Clave municipio", how="left")
DENUE_df

,Unnamed: 0,Unnamed: 0.1,Código Tipo de Industria,ID,Nombre de la Unidad Económica,Razón social,Código de la clase de actividad SCIAN,Nombre de clase de la actividad,Descripcion estrato personal ocupado,Tipo de vialidad,...,Manzana,NÃÂºmero de telÃÂ©fono,Correo electrÃÂ³nico,Sitio en Internet,Tipo de establecimiento,Latitud,Longitud,Fecha de incorporación al DENUE,Longitud_avg,Latitud_avg
0,0,174704,46,2511586,LONJA MERCANTIL HERNANDEZ,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CALLE,...,4,7.171710e+09,NaN,NaN,Fijo,19.069133,-99.611156,jul-10,-99.592760,19.093128
1,1,540472,81,2363713,ESTÃÂTICA UNISEX DIANA,NaN,812110,Salones y clÃÂ­nicas de belleza y peluquerÃÂ­as,0 a 5 personas,CALLE,...,12,NaN,NaN,NaN,Fijo,19.290680,-98.902444,dic-14,-98.892210,19.317269
2,2,23013,31,2032449,TORTILLERÃÂA 599,NaN,311830,ElaboraciÃÂ³n de tortillas de maÃÂ­z y molie...,0 a 5 personas,CALLE,...,5,NaN,NaN,NaN,Fijo,19.389040,-99.015859,dic-14,-99.020586,19.414493
3,3,86301,46,2002299,ABARROTES SIN NOMBRE,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,AVENIDA,...,8,NaN,NaN,NaN,Fijo,19.680749,-99.136141,jul-10,-99.124581,19.678139
4,4,399216,56,2249276,INTERNET MIP,NaN,561432,Servicios de acceso a computadoras,0 a 5 personas,CALLE,...,16,NaN,NaN,NaN,Fijo,19.787891,-99.055222,dic-14,-99.094497,19.802649
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72665,72665,534754,81,2505632,ESTÃÂTICA PLAZA,NaN,812110,Salones y clÃÂ­nicas de belleza y peluquerÃÂ­as,0 a 5 personas,CALLE,...,16,7.222082e+09,FROLOPZ31@YAHOO.COM.MX,NaN,Fijo,19.252294,-99.604720,jul-10,-99.601076,19.258685
72666,72666,407809,61,2018895,ESCUELA PRIMARIA 5 DE MAYO,NaN,611122,Escuelas de educaciÃÂ³n primaria del sector p...,6 a 10 personas,CALLE,...,19,5.557887e+09,NaN,NaN,Fijo,19.529771,-99.045686,jul-10,-99.038478,19.562241
72667,72667,186032,46,2544866,MISCELÃÂNEA ALVAREZ,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CALLE,...,24,NaN,NaN,NaN,Fijo,19.412025,-99.522470,jul-10,-99.520145,19.407205
72668,72668,207159,46,2373840,MISCELÃÂNEA LOS TRES ANGELITOS,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CALLE,...,29,NaN,NaN,NaN,Fijo,19.263108,-98.911619,dic-14,-98.891735,19.260208
72669,72669,400987,56,2549759,KRASH,NaN,561432,Servicios de acceso a computadoras,0 a 5 personas,CALLE,...,28,NaN,NaN,NaN,Fijo,19.806111,-99.717500,jul-10,-99.655555,19.745255

In [13]:
Micro_df = DENUE_df.loc[DENUE_df["Company Size"]=="Micro"]
locations_Micro = Micro_df[["Latitud", "Longitud"]]
# Fill NaN values and convert to float
rating_Micro = Micro_df["Company Size (int)"]#.astype(float)
rating_Medium = Medium_df["Company Size (int)"]

Medium_df = DENUE_df.loc[DENUE_df["Company Size"]=="Mediana"]
locations_Medium = Medium_df[["Latitud", "Longitud"]]








# Plot Heatmap
fig = gmaps.figure()

# Create layers
#symbols = gmaps.symbol_layer(locations, fill_color='red', stroke_color='red')
heat_layer = gmaps.heatmap_layer(locations_Micro, weights=rating_Micro, 
                                 dissipating=False, max_intensity=50,
                                 point_radius=0.005,gradient = [(0,0,0,0),"gray","black"])

heat_layer2 = gmaps.heatmap_layer(locations_Medium, weights=rating_Medium, 
                                 dissipating=False, max_intensity=50,
                                 point_radius=0.005,gradient = [(0,0,0,0),"aqua","blue"])
# Add layer
fig.add_layer(heat_layer)
fig.add_layer(heat_layer2)
#fig.add_layer(symbols)
# Display figure
fig

Figure(layout=FigureLayout(height='420px'))