# Data representation with Heat Maps.

In [1]:
# Dependencies
import requests
import json
import pandas as pd
import gmaps

# Google developer API key
from config import gkey

gmaps.configure(api_key=gkey)

In [2]:
#DENUE_df = pd.read_csv("Resources/DENUE_Filtered_complete.csv")
DENUE_df = pd.read_csv("Output/DENUE_Filtered.csv")
display(DENUE_df)
long_and_lat_df = pd.read_csv("Resources/Long_and_Lat_by_municip.csv")
display(long_and_lat_df)

C:\ProgramData\Miniconda3\envs\BootCamp\lib\site-packages\IPython\core\interactiveshell.py:3051: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,Unnamed: 0.1,Código Tipo de Industria,ID,Nombre de la Unidad Económica,Razón social,Código de la clase de actividad SCIAN,Nombre de clase de la actividad,Descripcion estrato personal ocupado,Tipo de vialidad,...,Localidad,Área geoestadí­stica básica,Manzana,NÃÂºmero de telÃÂ©fono,Correo electrÃÂ³nico,Sitio en Internet,Tipo de establecimiento,Latitud,Longitud,Fecha de incorporación al DENUE
0,0,174704,46,2511586,LONJA MERCANTIL HERNANDEZ,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CALLE,...,SAN BARTOLOMÃÂ ATLATLAHUCA,216,4,7.171710e+09,NaN,NaN,Fijo,19.069133,-99.611156,jul-10
1,1,540472,81,2363713,ESTÃÂTICA UNISEX DIANA,NaN,812110,Salones y clÃÂ­nicas de belleza y peluquerÃÂ­as,0 a 5 personas,CALLE,...,IXTAPALUCA,904,12,NaN,NaN,NaN,Fijo,19.290680,-98.902444,dic-14
2,2,23013,31,2032449,TORTILLERÃÂA 599,NaN,311830,ElaboraciÃÂ³n de tortillas de maÃÂ­z y molie...,0 a 5 personas,CALLE,...,CIUDAD NEZAHUALCÃÂYOTL,1289,5,NaN,NaN,NaN,Fijo,19.389040,-99.015859,dic-14
3,3,86301,46,2002299,ABARROTES SIN NOMBRE,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,AVENIDA,...,TULTEPEC,335,8,NaN,NaN,NaN,Fijo,19.680749,-99.136141,jul-10
4,4,399216,56,2249276,INTERNET MIP,NaN,561432,Servicios de acceso a computadoras,0 a 5 personas,CALLE,...,SAN SEBASTIÃÂN,359,16,NaN,NaN,NaN,Fijo,19.787891,-99.055222,dic-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72665,72665,534754,81,2505632,ESTÃÂTICA PLAZA,NaN,812110,Salones y clÃÂ­nicas de belleza y peluquerÃÂ­as,0 a 5 personas,CALLE,...,METEPEC,563,16,7.222082e+09,FROLOPZ31@YAHOO.COM.MX,NaN,Fijo,19.252294,-99.604720,jul-10
72666,72666,407809,61,2018895,ESCUELA PRIMARIA 5 DE MAYO,NaN,611122,Escuelas de educaciÃÂ³n primaria del sector p...,6 a 10 personas,CALLE,...,ECATEPEC DE MORELOS,741,19,5.557887e+09,NaN,NaN,Fijo,19.529771,-99.045686,jul-10
72667,72667,186032,46,2544866,MISCELÃÂNEA ALVAREZ,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CALLE,...,XONACATLÃÂN,43,24,NaN,NaN,NaN,Fijo,19.412025,-99.522470,jul-10
72668,72668,207159,46,2373840,MISCELÃÂNEA LOS TRES ANGELITOS,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CALLE,...,CHALCO DE DÃÂAZ COVARRUBIAS,081A,29,NaN,NaN,NaN,Fijo,19.263108,-98.911619,dic-14
72669,72669,400987,56,2549759,KRASH,NaN,561432,Servicios de acceso a computadoras,0 a 5 personas,CALLE,...,SAN MARCOS TLAZALPAN,110,28,NaN,NaN,NaN,Fijo,19.806111,-99.717500,jul-10

     Clave municipio  Longitud_avg  Latitud_avg
0                  1    -99.859455    19.946281
1                  2    -98.946145    19.616658
2                  3    -99.837060    20.106613
3                  4    -99.891648    18.866239
4                  5    -99.760391    19.346721
..               ...           ...          ...
120              121    -99.213019    19.652518
121              122    -98.941004    19.289142
122              123   -100.298548    18.921607
123              124   -100.129101    19.648330
124              125    -99.053623    19.688031

[125 rows x 3 columns]

In [3]:
list(DENUE_df["Descripcion estrato personal ocupado"].unique())

['0 a 5 personas',
 '6 a 10 personas',
 '11 a 30 personas',
 '31 a 50 personas',
 '51 a 100 personas',
 '101 a 250 personas',
 '251 y más personas']

In [4]:
list(DENUE_df["Descripcion estrato personal ocupado"].unique())

['0 a 5 personas',
 '6 a 10 personas',
 '11 a 30 personas',
 '31 a 50 personas',
 '51 a 100 personas',
 '101 a 250 personas',
 '251 y más personas']

In [5]:
Size_dict={'0 a 5 personas':1,
           '6 a 10 personas':2,
           '11 a 30 personas':3,
           "31 a 50 personas":4,
           '51 a 100 personas':5,
           '101 a 250 personas':6,
           '251 y más personas':7}
Size_dict2={'0 a 5 personas':"Micro",
           '6 a 10 personas':"Micro",
           '11 a 30 personas':"Pequeña",
           "31 a 50 personas":"Pequeña",
           '51 a 100 personas':"Mediana",
           '101 a 250 personas':"Mediana",
           '251 y más personas':"Grande"}

DENUE_df["Company Size"]=DENUE_df["Descripcion estrato personal ocupado"].astype(str)
DENUE_df["Company Size (int)"]=DENUE_df["Descripcion estrato personal ocupado"].astype(str)
DENUE_df=DENUE_df.replace({"Company Size (int)": Size_dict})
DENUE_df=DENUE_df.replace({"Company Size": Size_dict2})


DENUE_df

,Unnamed: 0,Unnamed: 0.1,Código Tipo de Industria,ID,Nombre de la Unidad Económica,Razón social,Código de la clase de actividad SCIAN,Nombre de clase de la actividad,Descripcion estrato personal ocupado,Tipo de vialidad,...,Manzana,NÃÂºmero de telÃÂ©fono,Correo electrÃÂ³nico,Sitio en Internet,Tipo de establecimiento,Latitud,Longitud,Fecha de incorporación al DENUE,Company Size,Company Size (int)
0,0,174704,46,2511586,LONJA MERCANTIL HERNANDEZ,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CALLE,...,4,7.171710e+09,NaN,NaN,Fijo,19.069133,-99.611156,jul-10,Micro,1
1,1,540472,81,2363713,ESTÃÂTICA UNISEX DIANA,NaN,812110,Salones y clÃÂ­nicas de belleza y peluquerÃÂ­as,0 a 5 personas,CALLE,...,12,NaN,NaN,NaN,Fijo,19.290680,-98.902444,dic-14,Micro,1
2,2,23013,31,2032449,TORTILLERÃÂA 599,NaN,311830,ElaboraciÃÂ³n de tortillas de maÃÂ­z y molie...,0 a 5 personas,CALLE,...,5,NaN,NaN,NaN,Fijo,19.389040,-99.015859,dic-14,Micro,1
3,3,86301,46,2002299,ABARROTES SIN NOMBRE,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,AVENIDA,...,8,NaN,NaN,NaN,Fijo,19.680749,-99.136141,jul-10,Micro,1
4,4,399216,56,2249276,INTERNET MIP,NaN,561432,Servicios de acceso a computadoras,0 a 5 personas,CALLE,...,16,NaN,NaN,NaN,Fijo,19.787891,-99.055222,dic-14,Micro,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72665,72665,534754,81,2505632,ESTÃÂTICA PLAZA,NaN,812110,Salones y clÃÂ­nicas de belleza y peluquerÃÂ­as,0 a 5 personas,CALLE,...,16,7.222082e+09,FROLOPZ31@YAHOO.COM.MX,NaN,Fijo,19.252294,-99.604720,jul-10,Micro,1
72666,72666,407809,61,2018895,ESCUELA PRIMARIA 5 DE MAYO,NaN,611122,Escuelas de educaciÃÂ³n primaria del sector p...,6 a 10 personas,CALLE,...,19,5.557887e+09,NaN,NaN,Fijo,19.529771,-99.045686,jul-10,Micro,2
72667,72667,186032,46,2544866,MISCELÃÂNEA ALVAREZ,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CALLE,...,24,NaN,NaN,NaN,Fijo,19.412025,-99.522470,jul-10,Micro,1
72668,72668,207159,46,2373840,MISCELÃÂNEA LOS TRES ANGELITOS,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CALLE,...,29,NaN,NaN,NaN,Fijo,19.263108,-98.911619,dic-14,Micro,1
72669,72669,400987,56,2549759,KRASH,NaN,561432,Servicios de acceso a computadoras,0 a 5 personas,CALLE,...,28,NaN,NaN,NaN,Fijo,19.806111,-99.717500,jul-10,Micro,1

In [6]:
DENUE_df = pd.merge(DENUE_df, long_and_lat_df, on="Clave municipio", how="left")
DENUE_df

,Unnamed: 0,Unnamed: 0.1,Código Tipo de Industria,ID,Nombre de la Unidad Económica,Razón social,Código de la clase de actividad SCIAN,Nombre de clase de la actividad,Descripcion estrato personal ocupado,Tipo de vialidad,...,Correo electrÃÂ³nico,Sitio en Internet,Tipo de establecimiento,Latitud,Longitud,Fecha de incorporación al DENUE,Company Size,Company Size (int),Longitud_avg,Latitud_avg
0,0,174704,46,2511586,LONJA MERCANTIL HERNANDEZ,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CALLE,...,NaN,NaN,Fijo,19.069133,-99.611156,jul-10,Micro,1,-99.592760,19.093128
1,1,540472,81,2363713,ESTÃÂTICA UNISEX DIANA,NaN,812110,Salones y clÃÂ­nicas de belleza y peluquerÃÂ­as,0 a 5 personas,CALLE,...,NaN,NaN,Fijo,19.290680,-98.902444,dic-14,Micro,1,-98.892210,19.317269
2,2,23013,31,2032449,TORTILLERÃÂA 599,NaN,311830,ElaboraciÃÂ³n de tortillas de maÃÂ­z y molie...,0 a 5 personas,CALLE,...,NaN,NaN,Fijo,19.389040,-99.015859,dic-14,Micro,1,-99.020586,19.414493
3,3,86301,46,2002299,ABARROTES SIN NOMBRE,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,AVENIDA,...,NaN,NaN,Fijo,19.680749,-99.136141,jul-10,Micro,1,-99.124581,19.678139
4,4,399216,56,2249276,INTERNET MIP,NaN,561432,Servicios de acceso a computadoras,0 a 5 personas,CALLE,...,NaN,NaN,Fijo,19.787891,-99.055222,dic-14,Micro,1,-99.094497,19.802649
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72665,72665,534754,81,2505632,ESTÃÂTICA PLAZA,NaN,812110,Salones y clÃÂ­nicas de belleza y peluquerÃÂ­as,0 a 5 personas,CALLE,...,FROLOPZ31@YAHOO.COM.MX,NaN,Fijo,19.252294,-99.604720,jul-10,Micro,1,-99.601076,19.258685
72666,72666,407809,61,2018895,ESCUELA PRIMARIA 5 DE MAYO,NaN,611122,Escuelas de educaciÃÂ³n primaria del sector p...,6 a 10 personas,CALLE,...,NaN,NaN,Fijo,19.529771,-99.045686,jul-10,Micro,2,-99.038478,19.562241
72667,72667,186032,46,2544866,MISCELÃÂNEA ALVAREZ,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CALLE,...,NaN,NaN,Fijo,19.412025,-99.522470,jul-10,Micro,1,-99.520145,19.407205
72668,72668,207159,46,2373840,MISCELÃÂNEA LOS TRES ANGELITOS,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CALLE,...,NaN,NaN,Fijo,19.263108,-98.911619,dic-14,Micro,1,-98.891735,19.260208
72669,72669,400987,56,2549759,KRASH,NaN,561432,Servicios de acceso a computadoras,0 a 5 personas,CALLE,...,NaN,NaN,Fijo,19.806111,-99.717500,jul-10,Micro,1,-99.655555,19.745255

In [7]:
Micro_df = DENUE_df.loc[DENUE_df["Company Size"]=="Micro"]
locations_Micro = Micro_df[["Latitud", "Longitud"]]

Small_df = DENUE_df.loc[DENUE_df["Company Size"]=="Pequeña"]
locations_Small = Small_df[["Latitud", "Longitud"]]

Medium_df = DENUE_df.loc[DENUE_df["Company Size"]=="Mediana"]
locations_Medium = Medium_df[["Latitud", "Longitud"]]

Large_df = DENUE_df.loc[DENUE_df["Company Size"]=="Grande"]
locations_Large = Large_df[["Latitud", "Longitud"]]


rating_Micro = Micro_df["Company Size (int)"]#.astype(float)
rating_Small = Small_df["Company Size (int)"]
rating_Medium = Medium_df["Company Size (int)"]#.astype(float)
rating_Large = Large_df["Company Size (int)"]

In [8]:
# Plot Heatmap
fig = gmaps.figure()

# Create layers
#symbols = gmaps.symbol_layer(locations, fill_color='red', stroke_color='red')
heat_layer1 = gmaps.heatmap_layer(locations_Micro, weights=rating_Micro, 
                                 dissipating=False, max_intensity=1,
                                 point_radius=0.005,gradient = [(0,0,0,0),"blue","blue"])

heat_layer2 = gmaps.heatmap_layer(locations_Small, weights=rating_Small, 
                                 dissipating=False, max_intensity=1,
                                 point_radius=0.005,gradient = [(0,0,0,0),"yellow","yellow"])

heat_layer3 = gmaps.heatmap_layer(locations_Medium, weights=rating_Medium, 
                                 dissipating=False, max_intensity=1,
                                 point_radius=0.005,gradient = [(0,0,0,0),"green","green"])

heat_layer4 = gmaps.heatmap_layer(locations_Large, weights=rating_Large, 
                                 dissipating=False, max_intensity=1,
                                 point_radius=0.005,gradient = [(0,0,0,0),"red","red"])



# Add layer
fig.add_layer(heat_layer1)
fig.add_layer(heat_layer2)
fig.add_layer(heat_layer3)
fig.add_layer(heat_layer4)
#fig.add_layer(symbols)
# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
Municipal_df = pd.read_csv("Resources/municipalpoverty.csv")
display(Municipal_df)

Municipal_df["entidad_federativa"].unique()

,clave_entidad,entidad_federativa,clave_municipio,municipio,poblacion,pobreza,pobreza_pob,pobreza_e,pobreza_e_pob,pobreza_m,...,ic_ali,ic_ali_pob,carencias,carencias_pob,carencias3,carencias3_pob,plb,plb_pob,plbm,plbm_pob
0,1,Aguascalientes,1001,Aguascalientes,"861,446",26.1,"224,949",1.6,"13,650",24.5,...,18,"154,658",52.6,"452,753",7.3,"63,220",37.6,"323,590",10,"86,166"
1,1,Aguascalientes,1002,Asientos,"46,624",54,"25,169",4.4,"2,067",49.5,...,24.7,"11,494",83,"38,713",14.1,"6,594",61.7,"28,745",24.4,"11,394"
2,1,Aguascalientes,1003,Calvillo,"52,773",56.8,"29,951",3.1,"1,650",53.6,...,17.3,"9,148",84.3,"44,513",10.5,"5,528",63.1,"33,299",26.8,"14,118"
3,1,Aguascalientes,1004,Cosío,"15,321",43.2,"6,620",2.8,432,40.4,...,20.7,"3,175",75.9,"11,623",9.9,"1,522",51.2,"7,852",16.6,"2,546"
4,1,Aguascalientes,1005,Jesús María,"125,750",25,"31,479",1.7,"2,095",23.4,...,18.7,"23,562",63.1,"79,310",11.3,"14,225",31.6,"39,794",7.9,"9,984"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2452,32,Zacatecas,32054,Villa Hidalgo,"18,155",71.8,"13,040",9.2,"1,674",62.6,...,24.4,"4,435",88.8,"16,123",16.7,"3,034",76.8,"13,934",38.5,"6,983"
2453,32,Zacatecas,32055,Villanueva,"29,957",61,"18,269",6.9,"2,071",54.1,...,22.5,"6,747",84.3,"25,247",14.7,"4,394",68.2,"20,433",28.7,"8,590"
2454,32,Zacatecas,32056,Zacatecas,"150,854",25.9,"39,133",1.8,"2,768",24.1,...,16.2,"24,459",54.2,"81,808",6.5,"9,817",34.9,"52,656",8.5,"12,882"
2455,32,Zacatecas,32057,Trancoso,"18,716",63.1,"11,815",7.7,"1,439",55.4,...,28.9,"5,406",83.8,"15,677",16.3,"3,057",70.7,"13,235",30.1,"5,642"
2456,32,Zacatecas,32058,Santa María de la Paz,"2,658",57.4,"1,525",5.9,156,51.5,...,12.2,324,87.9,"2,337",14.4,382,60.1,"1,598",26.5,704

array(['Aguascalientes', 'Baja California', 'Baja California Sur',
       'Campeche', 'Coahuila', 'Colima', 'Chiapas', 'Chihuahua',
       'Distrito Federal', 'Durango', 'Guanajuato', 'Guerrero', 'Hidalgo',
       'Jalisco', 'México', 'Michoacán', 'Morelos', 'Nayarit',
       'Nuevo León', 'Oaxaca', 'Puebla', 'Querétaro', 'Quintana Roo',
       'San Luis Potosí', 'Sinaloa', 'Sonora', 'Tabasco', 'Tamaulipas',
       'Tlaxcala', 'Veracruz', 'Yucatán', 'Zacatecas'], dtype=object)

In [10]:
EdoMex_df = Municipal_df.loc[Municipal_df["entidad_federativa"]=="México"]
#locations_Micro = Micro_df[["Latitud", "Longitud"]]

EdoMex_df

,clave_entidad,entidad_federativa,clave_municipio,municipio,poblacion,pobreza,pobreza_pob,pobreza_e,pobreza_e_pob,pobreza_m,...,ic_ali,ic_ali_pob,carencias,carencias_pob,carencias3,carencias3_pob,plb,plb_pob,plbm,plbm_pob
656,15,México,15001,Acambay,"62,863",73.5,"46,233",19.8,"12,475",53.7,...,32.5,"20,455",95.2,"59,866",39.2,"24,627",75,"47,164",37.1,"23,336"
657,15,México,15002,Acolman,"171,774",56.2,"96,512",8.6,"14,715",47.6,...,22.8,"39,117",74.8,"128,479",19.2,"32,987",67.9,"116,692",24.3,"41,814"
658,15,México,15003,Aculco,"46,275",61.9,"28,628",10.7,"4,930",51.2,...,28.9,"13,384",93.2,"43,139",29,"13,408",63.6,"29,419",23.8,"10,993"
659,15,México,15004,Almoloya de Alquisiras,"14,115",73.4,"10,354",18.7,"2,638",54.7,...,26.2,"3,695",94.2,"13,299",34.4,"4,858",75.2,"10,616",37.5,"5,290"
660,15,México,15005,Almoloya de Juárez,"179,746",59.9,"107,654",12.6,"22,666",47.3,...,31,"55,796",82.5,"148,230",28.9,"51,862",66.2,"118,999",25.3,"45,397"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
776,15,México,15121,Cuautitlán Izcalli,"509,985",27.7,"141,173",2.8,"14,401",24.9,...,15.8,"80,357",48.4,"247,052",8.4,"43,048",43,"219,101",11.6,"59,110"
777,15,México,15122,Valle de Chalco Solidaridad,"452,170",59,"266,702",9.5,"42,778",49.5,...,24.4,"110,103",77.5,"350,239",21,"94,843",71.2,"321,840",27.8,"125,851"
778,15,México,15123,Luvianos,"24,639",84.9,"20,914",32.1,"7,911",52.8,...,29.3,"7,230",97.7,"24,073",44.7,"11,012",85.8,"21,145",54.4,"13,402"
779,15,México,15124,San José del Rincón,"84,040",76.3,"64,133",22.8,"19,120",53.6,...,18.6,"15,616",99.5,"83,641",48.7,"40,958",76.4,"64,231",39.4,"33,153"
780,15,México,15125,Tonanitla,"10,190",49.6,"5,055",5.1,519,44.5,...,17.6,"1,794",79.3,"8,080",14.7,"1,503",55.6,"5,669",19.1,"1,946"