In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from config import inegi_key #inegi token
from config import coneval_key #coneval
from config import gkey #google key

In [2]:
denue_filtered_df = pd.read_csv("Output/DENUE_Filtered.csv",encoding="ISO-8859-1")
denue_filtered_df

C:\Users\tato_\Anaconda3\envs\PythonData\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,Unnamed: 0.1,CÃ³digo Tipo de Industria,ID,Nombre de la Unidad EconÃ³mica,RazÃ³n social,CÃ³digo de la clase de actividad SCIAN,Nombre de clase de la actividad,Descripcion estrato personal ocupado,Tipo de vialidad,...,Localidad,Ãrea geoestadÃ­Â­stica bÃ¡sica,Manzana,NÃÂÃÂºmero de telÃÂÃÂ©fono,Correo electrÃÂÃÂ³nico,Sitio en Internet,Tipo de establecimiento,Latitud,Longitud,Fecha de incorporaciÃ³n al DENUE
0,0,174704,46,2511586,LONJA MERCANTIL HERNANDEZ,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CALLE,...,SAN BARTOLOMÃÂÃÂ ATLATLAHUCA,216,4,7.171710e+09,NaN,NaN,Fijo,19.069133,-99.611156,jul-10
1,1,540472,81,2363713,ESTÃÂÃÂTICA UNISEX DIANA,NaN,812110,Salones y clÃÂÃÂ­nicas de belleza y peluque...,0 a 5 personas,CALLE,...,IXTAPALUCA,904,12,NaN,NaN,NaN,Fijo,19.290680,-98.902444,dic-14
2,2,23013,31,2032449,TORTILLERÃÂÃÂA 599,NaN,311830,ElaboraciÃÂÃÂ³n de tortillas de maÃÂÃÂ­z...,0 a 5 personas,CALLE,...,CIUDAD NEZAHUALCÃÂÃÂYOTL,1289,5,NaN,NaN,NaN,Fijo,19.389040,-99.015859,dic-14
3,3,86301,46,2002299,ABARROTES SIN NOMBRE,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,AVENIDA,...,TULTEPEC,335,8,NaN,NaN,NaN,Fijo,19.680749,-99.136141,jul-10
4,4,399216,56,2249276,INTERNET MIP,NaN,561432,Servicios de acceso a computadoras,0 a 5 personas,CALLE,...,SAN SEBASTIÃÂÃÂN,359,16,NaN,NaN,NaN,Fijo,19.787891,-99.055222,dic-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72665,72665,534754,81,2505632,ESTÃÂÃÂTICA PLAZA,NaN,812110,Salones y clÃÂÃÂ­nicas de belleza y peluque...,0 a 5 personas,CALLE,...,METEPEC,563,16,7.222082e+09,FROLOPZ31@YAHOO.COM.MX,NaN,Fijo,19.252294,-99.604720,jul-10
72666,72666,407809,61,2018895,ESCUELA PRIMARIA 5 DE MAYO,NaN,611122,Escuelas de educaciÃÂÃÂ³n primaria del sect...,6 a 10 personas,CALLE,...,ECATEPEC DE MORELOS,741,19,5.557887e+09,NaN,NaN,Fijo,19.529771,-99.045686,jul-10
72667,72667,186032,46,2544866,MISCELÃÂÃÂNEA ALVAREZ,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CALLE,...,XONACATLÃÂÃÂN,43,24,NaN,NaN,NaN,Fijo,19.412025,-99.522470,jul-10
72668,72668,207159,46,2373840,MISCELÃÂÃÂNEA LOS TRES ANGELITOS,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CALLE,...,CHALCO DE DÃÂÃÂAZ COVARRUBIAS,081A,29,NaN,NaN,NaN,Fijo,19.263108,-98.911619,dic-14
72669,72669,400987,56,2549759,KRASH,NaN,561432,Servicios de acceso a computadoras,0 a 5 personas,CALLE,...,SAN MARCOS TLAZALPAN,110,28,NaN,NaN,NaN,Fijo,19.806111,-99.717500,jul-10

In [9]:
grouped_denue_filtered_df = denue_filtered_df.groupby('Clave municipio')
grouped_denue_filtered_df.head()

,Unnamed: 0,Unnamed: 0.1,CÃ³digo Tipo de Industria,ID,Nombre de la Unidad EconÃ³mica,RazÃ³n social,CÃ³digo de la clase de actividad SCIAN,Nombre de clase de la actividad,Descripcion estrato personal ocupado,Tipo de vialidad,...,Localidad,Ãrea geoestadÃ­Â­stica bÃ¡sica,Manzana,NÃÂÃÂºmero de telÃÂÃÂ©fono,Correo electrÃÂÃÂ³nico,Sitio en Internet,Tipo de establecimiento,Latitud,Longitud,Fecha de incorporaciÃ³n al DENUE
0,0,174704,46,2511586,LONJA MERCANTIL HERNANDEZ,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CALLE,...,SAN BARTOLOMÃÂÃÂ ATLATLAHUCA,216,4,7.171710e+09,NaN,NaN,Fijo,19.069133,-99.611156,jul-10
1,1,540472,81,2363713,ESTÃÂÃÂTICA UNISEX DIANA,NaN,812110,Salones y clÃÂÃÂ­nicas de belleza y peluque...,0 a 5 personas,CALLE,...,IXTAPALUCA,904,12,NaN,NaN,NaN,Fijo,19.290680,-98.902444,dic-14
2,2,23013,31,2032449,TORTILLERÃÂÃÂA 599,NaN,311830,ElaboraciÃÂÃÂ³n de tortillas de maÃÂÃÂ­z...,0 a 5 personas,CALLE,...,CIUDAD NEZAHUALCÃÂÃÂYOTL,1289,5,NaN,NaN,NaN,Fijo,19.389040,-99.015859,dic-14
3,3,86301,46,2002299,ABARROTES SIN NOMBRE,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,AVENIDA,...,TULTEPEC,335,8,NaN,NaN,NaN,Fijo,19.680749,-99.136141,jul-10
4,4,399216,56,2249276,INTERNET MIP,NaN,561432,Servicios de acceso a computadoras,0 a 5 personas,CALLE,...,SAN SEBASTIÃÂÃÂN,359,16,NaN,NaN,NaN,Fijo,19.787891,-99.055222,dic-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32680,32680,12555,31,2479456,PANADERÃÂÃÂA SAGRADO CORAZÃÂÃÂN DE JES...,NaN,311812,PanificaciÃÂÃÂ³n tradicional,0 a 5 personas,CALLE,...,OTZOLOAPAN,32,6,NaN,NaN,NaN,Fijo,19.116980,-100.296360,dic-14
37694,37694,144015,46,2526129,FARMACIA CRISTO REY,NaN,464111,Farmacias sin minisÃÂÃÂºper,0 a 5 personas,CALLE,...,SAN SIMÃÂÃÂN DE GUERRERO,36,32,NaN,NaN,NaN,Fijo,19.022494,-100.005793,jul-10
48479,48479,578474,81,2526098,TALACHERÃÂÃÂA MARTHITA,NaN,811191,ReparaciÃÂÃÂ³n menor de llantas,0 a 5 personas,CALLE,...,SAN SIMÃÂÃÂN DE GUERRERO,36,30,NaN,NaN,NaN,Fijo,19.024668,-100.005050,jul-10
56033,56033,218517,46,2480352,MISCELÃÂÃÂNEA SIN NOMBRE,NaN,461110,"Comercio al por menor en tiendas de abarrotes,...",0 a 5 personas,CERRADA,...,SAN SIMÃÂÃÂN DE GUERRERO,36,30,NaN,NaN,NaN,Fijo,19.024399,-100.004918,dic-14
64607,64607,533237,81,2526114,ESTÃÂÃÂTICA MEDUSAS,NaN,812110,Salones y clÃÂÃÂ­nicas de belleza y peluque...,0 a 5 personas,CALLE,...,SAN SIMÃÂÃÂN DE GUERRERO,36,8,NaN,NaN,NaN,Fijo,19.023000,-100.006270,jul-10

In [19]:
longandlat_df = pd.DataFrame(grouped_denue_filtered_df["Longitud"].mean())
longandlat_df["Latitud_avg"] = pd.DataFrame(grouped_denue_filtered_df["Latitud"].mean())
longandlat_df = longandlat_df.rename(columns={"Longitud":"Longitud_avg"})
longandlat_df.head()

                 Longitud_avg  Latitud_avg
Clave municipio
1                  -99.859455    19.946281
2                  -98.946145    19.616658
3                  -99.837060    20.106613
4                  -99.891648    18.866239
5                  -99.760391    19.346721

In [20]:
longandlat_df.to_csv("Resources/Long_and_Lat_by_municip.csv", index=True, header=True)