In [15]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [21]:
# Hide warning messages in notebook
import warnings
warnings.filterwarnings('ignore')

In [28]:
# File to Load (Remember to Change These)
municipio_pov_dataload = "municipalpoverty.csv"
municipio_df = pd.read_csv(municipio_pov_dataload)

In [53]:
municipaldata = pd.DataFrame(municipio_df)
new = municipaldata[['clave_entidad', 'entidad_federativa', 'clave_municipio', 'municipio', 'poblacion', 'pobreza', 'pobreza_pob']].copy()
new.head()

,clave_entidad,entidad_federativa,clave_municipio,municipio,poblacion,pobreza,pobreza_pob
0,1,Aguascalientes,1001,Aguascalientes,"861,446",26.1,"224,949"
1,1,Aguascalientes,1002,Asientos,"46,624",54,"25,169"
2,1,Aguascalientes,1003,Calvillo,"52,773",56.8,"29,951"
3,1,Aguascalientes,1004,Cosío,"15,321",43.2,"6,620"
4,1,Aguascalientes,1005,Jesús María,"125,750",25,"31,479"

In [55]:
mexico_state_df = new[new['entidad_federativa'].str.contains("México")]
poverty_by_municipality_df = mexico_state_df.rename(columns={"clave_entidad": "State ID",
                                    "entidad_federativa": "State", 
                                    "clave_municipio": "Municipality ID",
                                    "municipio": "Municipality",
                                    "poblacion": "Population",
                                    "pobreza": "% Poverty", 
                                    "pobreza_pob": "Total Population in Poverty"})

poverty_by_municipality_df

,State ID,State,Municipality ID,Municipality,Population,% Poverty,Total Population in Poverty
656,15,México,15001,Acambay,"62,863",73.5,"46,233"
657,15,México,15002,Acolman,"171,774",56.2,"96,512"
658,15,México,15003,Aculco,"46,275",61.9,"28,628"
659,15,México,15004,Almoloya de Alquisiras,"14,115",73.4,"10,354"
660,15,México,15005,Almoloya de Juárez,"179,746",59.9,"107,654"
...,...,...,...,...,...,...,...
776,15,México,15121,Cuautitlán Izcalli,"509,985",27.7,"141,173"
777,15,México,15122,Valle de Chalco Solidaridad,"452,170",59,"266,702"
778,15,México,15123,Luvianos,"24,639",84.9,"20,914"
779,15,México,15124,San José del Rincón,"84,040",76.3,"64,133"
780,15,México,15125,Tonanitla,"10,190",49.6,"5,055"